### ISSUE TITLE
No overwrite?

### ISSUE THREAD

**Issue by joserick** [f9webltd/laravel-meta#24]
Hi,

I'm trying to overwrite default meta but it doesn't work.

f9web-laravel-meta.php
```php
  'defaults' => [
      'property:og:data' => 'ZZZ',
  ];
```
MyController
```php
  meta()->set('property:og:data', 'YYY');
  // OR
  meta()->forget('property:og:data')
       ->forget('og:data')
       ->set('property:og:data', 'YYY');
```
Header
```html
  <meta property="og:data" content="ZZZ">
```

is there a way to override it?

**Comment by ultrono** [comment]
Hi,

I think that may be a small bug. I've (incorrectly) rendered the default tags before outputting tags you've set, which is what I suspect is causing the issue here. Additionally the package doesn't have any tests covering overriding default tags.

I'd be open to PR to fix this behaviour as it's definitely a bug.

Cheers
